services:
  zinc:
    image: public.ecr.aws/zinclabs/zincsearch:latest
    container_name: zincsearch
    ports:
      - "5000:4080" # External access via http://localhost:5000
    environment:
      ZINC_DATA_PATH: "/data"
      ZINC_FIRST_ADMIN_USER: "admin"
      ZINC_FIRST_ADMIN_PASSWORD: "admin"
    volumes:
      - ./zincsearch/data:/data
    user: "1000:1000"

  indexer:
    build:
      context: ./indexer
      dockerfile: Dockerfile
    container_name: enron_indexer
    depends_on: 
      - zinc
    environment:
      ZINCSEARCH_URL: "http://zinc:4080" # uses internal port
      SKIP_PROFILING: "TRUE"

  web-client:
    build:
      context: ./email-viewer
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "http://localhost:5000"  # Point to the host's port where Zinc is mapped
        VITE_API_USER: "admin"
        VITE_API_USER_PWD: "admin"
    container_name: email_viewer
    ports:
      - "3000:80"  # External access via http://localhost:3000
    depends_on:
      - zinc


